新しいメッセージtypeに対応しました
RoboDragons/ssl-logtools pull request #1
Opened 2024-08-22 05:22 UTC by tomoakiwakawaka

2024-08-22 21:41 UTC, masa-ito4github requested changes
@tomoakiwakawaka めっちゃ変更点ある！？と思ったら、cmake関係のログばっかりじゃないっすか🤣


2点修正して、pushし直してほしい。
- makeとcmakeをcleanした状態に（個人情報含んでるしね）
- clang適用はいったん除いてください（本質的な差分のみにしてほしい）

2024-08-22 21:41 UTC, masa-ito4github commented on src/logplayer/player.h
> +    Network* m_index;
この追加は何のため？

2024-08-22 22:57 UTC, masa-ito4github commented
@tomoakiwakawaka this is a test comment for notification on slack

2024-08-23 07:17 UTC, masa-ito4github commented
@tomoakiwakawaka 作業ありがとう．しかし，ひとつのファイルが削除されただけやで．File changed がもともと40個あるのは気づいてる？そのうち，本質的な変更がなされているは2つ．あとの38個はcmake（とmake）で生成されたファイル群．

clangで整形したのを巻き戻すのは難しい？

2024-08-23 07:19 UTC, masa-ito4github commented on src/logplayer/player.h
> +    Network* m_index;
@tomoakiwakawaka やりとりなしのResolve（解決）はだめよー（裏で会話してたとしても，ここに記録を残すことに意味があります）

2024-08-26 04:44 UTC, tomoakiwakawaka commented
やってみます！！

2024-09-05 09:32 UTC, tomoakiwakawaka commented
変更点
player.cc 158-164
player.h 54のm.index

2024-09-05 11:54 UTC, masa-ito4github commented on src/common/format/message_type.h
> +    MESSAGE_SSL_INDEX_2021=6
@tomoakiwakawaka 何を参考にして，これらを定義したの？

2024-09-05 11:55 UTC, masa-ito4github commented on src/logplayer/player.h
> +    Network* m_index;
@tomoakiwakawaka 何を参考にして，これを定義したの？

2024-09-05 12:01 UTC, masa-ito4github commented
> 変更点 player.cc 158-164 player.h 54のm.index @masa-ito4github

@tomoakiwakawaka 
- https://github.com/RoboDragons/ssl-logtools/pull/1#discussion_r1745326349
- https://github.com/RoboDragons/ssl-logtools/pull/1#discussion_r1745324671
それぞれに対する回答をください（コード内にコメントもあったほうがよい）．

（もっと前に要求すべきだったけど）修正によって改善したことを示す比較結果がほしい．具体的には

- 変更前にエラー（じゃなくてワーニングだっけ？）が出力されていた様子，
- 変更後は追加したラベル `MESSAGE_SSL_VISION_TRACKER_2020` と `MESSAGE_SSL_INDEX_2021` のデータが読み込めている様子

がわかるものを示して，説明してほしいっす．

2024-09-11 10:10 UTC, tomoakiwakawaka commented
[https://ssl.robocup.org/game-logs/](url)
このページを参考にしました．

インデックス付きログファイルは、最後のメッセージとして MESSAGE_SSL_INDEX_2021 タイプのメッセージを持つので，最後のメッセージを受け取るためにm_indexというあらたなポインタを作りました．

https://github.com/user-attachments/assets/63ff7d60-add9-4c29-ae72-33de3fb9184b

https://github.com/user-attachments/assets/69831c6d-bad6-402b-b125-c289bc98c82c

2024-09-18 05:36 UTC, masa-ito4github commented on src/logplayer/player.h
> +    Network* m_index;
https://github.com/RoboDragons/ssl-logtools/pull/1#issuecomment-2343214458
により了解

2024-09-18 05:36 UTC, masa-ito4github commented on src/common/format/message_type.h
> +    MESSAGE_SSL_INDEX_2021=6
https://github.com/RoboDragons/ssl-logtools/pull/1#issuecomment-2343214458
により了解

2024-09-18 05:38 UTC, masa-ito4github approved these changes
@tomoakiwakawaka 

https://github.com/RoboDragons/ssl-logtools/pull/1#issuecomment-2343214458

の一部動画が差し替え見込みで approve します．本家でPReqするときにはコードに clang かけないように注意してくださいねー．

2024-09-19 05:33 UTC, merged